src/oidcc.erl
src/oidcc_openid_provider.erl

dont enforce optionial information for keys 
use client_secret_basic supported allowed

Changes to interop with IAM

---

src/oidcc.erl
src/oidcc_http_handler.erl
src/oidcc_session.erl
src/oidcc_session_mgr.erl
src/oidcc_session_sup.erl
test/oidcc_session_mgr_test.erl
test/oidcc_session_test.erl

at creation of the session the provider is set and checked for
PKCE support, in case it is supported it will be used.
The preferred method is S256, falling back to plain if not
supported.
Test have been adjusted.

Add PKCE S256 and plain

---

src/oidcc.erl

as it does not only retrieve an access token but a whole OpenId Connect token set

rename retrieve_access_token to retrieve_fresh_token

---

src/oidcc.erl
src/oidcc_openid_provider.erl
test/oidcc_openid_provider_test.erl

some provider do not publish the supported authmetods, in this case 'basic auth' is according to the specs the fallback. Implemented in first commit.
According to the specs the Issuer can be derived from the configuration endpoint, implemented in the 
second commit; fix #64 
Needed to adjust test accordingly

Fix authmethods and Issuer verification

---

src/oidcc_http_cache.erl
src/oidcc_http_util.erl
src/oidcc_sup.erl
test/oidcc_http_cache_test.erl
test/oidcc_http_util_test.erl

introducing two new settings:
- http_cache_duration: how long (in seconds) to keep the data cached, default none (not active)
- http_cache_clean: number of seconds after which a cache clean is triggered, it is only checke on storing data in cache, not reading, default 60

implement basic sync http caching, fix #142

---

src/oidcc_session.erl

We had several cases with using an Okta OpenID Connect link that the PKCE verification failed. It seemed to be the case when the base64 encoding needed the `=` character to pad the string the PKCE verification would fail. Looking at the spec, this is indeed a non-allowed character:
> code_verifier = high-entropy cryptographic random STRING using the unreserved characters [A-Z] / [a-z] / [0-9] / "-" / "." / "_" / "~" from Section 2.3 of [RFC3986], with a minimum length of 43 characters and a maximum length of 128 characters.
(Source: https://tools.ietf.org/html/rfc7636)
For some generated verifiers the PKCE verification would succeed, for other it would fail. By using the more strict `base64url` method, we solve the issue.

Fixed encoding of CodeVerifier

---

src/oidcc_http_util.erl

Needed to make it work with `https://idp.bexio.com/.well-known/openid-configuration`

Improve HostName Check for Wildcard Certificates

---

lib/oidcc/provider_configuration.ex
lib/oidcc/token.ex
lib/oidcc/token_introspection.ex
lib/oidcc/userinfo.ex
mix.exs
rebar.config
src/oidcc_provider_configuration.erl
src/oidcc_token.erl
src/oidcc_token_introspection.erl
src/oidcc_userinfo.erl

Document Telemetry Events

---

README.md
lib/oidcc.ex
lib/oidcc/authorization.ex
lib/oidcc/client_context.ex
lib/oidcc/provider_configuration/worker.ex
lib/oidcc/token.ex
lib/oidcc/token_introspection.ex
lib/oidcc/userinfo.ex
src/oidcc_provider_configuration.erl
src/oidcc_provider_configuration_worker.erl
test/oidcc/authorization_test.exs
test/oidcc/client_context_test.exs
test/oidcc/provider_configuration/worker_test.exs
test/oidcc_client_context_SUITE.erl
test/oidcc_provider_configuration_SUITE.erl
test/oidcc_provider_configuration_worker_SUITE.erl
test/oidcc_test.exs

Check Issuer on Config Load

---

src/oidcc_authorization.erl
src/oidcc_jwt_util.erl
test/oidcc_authorization_test.erl
test/oidcc_token_test.erl

Support JWT authorization request parameter

---

include/oidcc_client_context.hrl
lib/oidcc.ex
lib/oidcc/client_context.ex
src/oidcc.erl
src/oidcc_authorization.erl
src/oidcc_client_context.erl
src/oidcc_token.erl
test/oidcc_token_test.erl

Support client_secret_jwt & private_key_jwt for token auth

---

.github/workflows/branch_main.yml
.github/workflows/part_publish.yml
.github/workflows/pr.yml
.github/workflows/tag-beta.yml
.github/workflows/tag-stable.yml

Setup GitHub Actions Package Publish

---

include/oidcc_client_context.hrl
lib/oidcc.ex
lib/oidcc/client_context.ex
lib/oidcc/logout.ex
src/oidcc.erl
src/oidcc_authorization.erl
src/oidcc_client_context.erl
src/oidcc_logout.erl
src/oidcc_token.erl
src/oidcc_token_introspection.erl
src/oidcc_userinfo.erl
test/oidcc/logout_test.exs
test/oidcc_SUITE.erl
test/oidcc_logout_test.erl
test/oidcc_test.exs

Differentiate between authenticated and unauthenticated client contexts

---

src/oidcc_authorization.erl
test/oidcc_authorization_SUITE.erl
test/oidcc_authorization_test.erl

Handle optional config parameters in authorization request_object generation

---

src/oidcc_authorization.erl
src/oidcc_token.erl
test/oidcc_authorization_test.erl
test/oidcc_token_test.erl

Ran into this while trying to use `max_clock_skew` to investigate something else. This didn't appear to be covered by tests, but happy to add them if you can point me in the right direction.

fix: `application:get_env/2` returns `{ok, Value}`

---

src/oidcc_token.erl
test/oidcc_token_test.erl

Provide default for `token_endpoint_auth_signing_alg_values_supported`

---

.github/workflows/part_test.yml
mix.exs

1.14.4 was the first Elixir release to support OTP 26: https://github.com/elixir-lang/elixir/releases/tag/v1.14.4
There doesn't appear to be anything about Oidcc which requires features in 1.15, so Oidcc can express support for slightly earlier versions.

feat: support Elixir 1.14.4+

---

src/oidcc_jwt_util.erl
src/oidcc_token.erl
test/oidcc_token_test.erl

By default, JOSE disables verification of `none` alg JWTs, for (reasonable) security preferences. However,
`oidcc-client-test-idtoken-sig-none` says this is an optionally supported use case. This updates the implementation of `verify_signature` to return an error with the JWT/JWS values even when JOSE is configured not to allow `none` signatures.

fix: support unsigned ID tokens even when JOSE disables them

---

README.md

Fixes: #296 
Closes https://github.com/erlef/oidcc/issues/296

Specify minimum OTP26 version requirement in the README.md

---

src/oidcc_authorization.erl
test/oidcc_authorization_test.erl

More notes in the individual commits, but the tl;dr;
- correct the sorting of signing/encryption algorithms
- put `url_extension` parameters in the URL even when using a `request` param

two bugs with `request` param

---

include/oidcc_token_introspection.hrl
lib/oidcc/token_introspection.ex
src/oidcc_auth_util.erl
src/oidcc_http_util.erl
src/oidcc_token.erl
src/oidcc_token_introspection.erl
test/oidcc_auth_util_test.erl
test/oidcc_token_introspection_test.erl
test/oidcc_token_test.erl

- allow client authentication types other than `client_secret_basic` (by extracting the code used in `oidcc_token`)
- include other values defined in https://datatracker.ietf.org/doc/html/rfc7662, as well as `extra` to include values outside the spec

introspection improvements

---

src/oidcc_authorization.erl
src/oidcc_jwt_util.erl
test/oidcc_authorization_test.erl
test/oidcc_token_test.erl

Two fixes that came up while validating the `private_key_jwt` auth method. With this, it passes the `client-oidcc-test-plan` suite.

two fixes with client JWK signing

---

src/oidcc_authorization.erl
src/oidcc_token.erl
test/oidcc_authorization_test.erl

Required for `https://sts.windows.net/{tenant}/` issuer, which does not specify `grant_types_supported` but still offers client credential tokens.

Introduce Quirks option to allow unsupported grant types

---

src/oidcc_token.erl
test/oidcc_token_test.erl

Allow to pass body_extension for token retrieval

---

src/oidcc_authorization.erl
src/oidcc_provider_configuration.erl
src/oidcc_token.erl
test/oidcc_authorization_test.erl
test/oidcc_provider_configuration_test.erl

I don't love this as a bulk override, but it seems easier than needing to add a specific quirk for each attribute that it's possible for an OP to get wrong?

feat: `document_overrides` quirk to patch invalid OIDD files

---

src/oidcc_token.erl
test/oidcc_token_test.erl

Properly Validate & Cast Token Responses (#306)

---

include/oidcc_provider_configuration.hrl
lib/oidcc/provider_configuration.ex
src/oidcc_provider_configuration.erl

- PAR: Pushed Authorization Requests
- JARM: JWT Secured Authorization Response Mode
- DPoP: Demonstrating Proof of Possession
Extracted from paulswartz/oidcc#3

feat: include config params for PAR, JARM, and DPoP

---

README.md
include/oidcc_client_registration.hrl
lib/oidcc/client_registration.ex
src/oidcc_auth_util.erl
src/oidcc_authorization.erl
src/oidcc_client_registration.erl
test/oidcc_authorization_SUITE.erl
test/oidcc_authorization_test.erl

RFC: https://datatracker.ietf.org/doc/html/rfc9126

feat: Pushed Authorization Request (PAR)

---

src/oidcc_authorization.erl
test/oidcc_authorization_test.erl

This wasn't validated by the conformance suite test I was using, nor my unit tests.

fix(PAR): ensure we don't send duplicate parameters

---

README.md
include/oidcc_client_registration.hrl
include/oidcc_token.hrl
lib/oidcc/client_registration.ex
lib/oidcc/token.ex
lib/oidcc/token/access.ex
src/oidcc_auth_util.erl
src/oidcc_authorization.erl
src/oidcc_client_registration.erl
src/oidcc_http_util.erl
src/oidcc_jwt_util.erl
src/oidcc_token.erl
src/oidcc_token_introspection.erl
src/oidcc_userinfo.erl
test/oidcc_authorization_test.erl
test/oidcc_token_test.erl
test/oidcc_userinfo_test.erl

[Demonstrating Proof of Possession (DPoP)](https://www.rfc-editor.org/rfc/rfc9449)

feat: Demonstrating Proof of Posession (DPoP)

---

src/oidcc_authorization.erl
src/oidcc_jwt_util.erl
src/oidcc_token.erl
src/oidcc_userinfo.erl
test/oidcc_authorization_test.erl
test/oidcc_token_test.erl
test/oidcc_userinfo_test.erl

feat: support encrypted ID tokens and Userinfo responses

---

lib/oidcc/token/access.ex
src/oidcc_http_util.erl
src/oidcc_token.erl
test/oidcc_token_test.erl
test/oidcc_userinfo_test.erl

https://gitlab.com/openid/conformance-suite/-/merge_requests/1354 has conformance tests which incorporate validation of the DPoP nonces, which uncovered a couple issues:
- we were providing the nonce in the claims as a list of numbers (charlist) instead of a binary
- `Oidcc.Token.Access.authorization_headers` didn't expose `opts` to provide the `dpop_nonce` value

fix: small fixes for DPoP

---

README.md
src/oidcc_authorization.erl
src/oidcc_profile.erl
test/oidcc_authorization_test.erl
test/oidcc_client_context_test.erl

I can't find any good documentation about it, but this is what's necessary to pass the conformance suite:
- require a "purpose" value in the request
- use the mTLS endpoints (with a certificate) even if we're not using mTLS authentication

feat: small features to support ConnectID.com.au profile

---

lib/oidcc/token.ex
src/oidcc_token.erl
test/oidcc_token_SUITE.erl
test/oidcc_token_test.erl

Many access tokens are JWTs, which clients can validate without needing to use the `token_introspection` endpoint. This allows multiple clients using the same issuer to use access tokens as a means of validation between them.

feat: function to locally validate a JWT

---

src/oidcc_profile.erl
test/oidcc_client_context_test.erl

This seems to be the reason the ConnectID profile required this change; it's also needed for the mTLS sender-constrained FAPI2 Security Profile conformance tests.

feat: profile for mTLS sender-constrained tokens

---

src/oidcc_backoff.erl
src/oidcc_client_context.erl
src/oidcc_provider_configuration_worker.erl
test/oidcc_backoff_test.erl
test/oidcc_provider_configuration_worker_test.erl

Implement backoff algorithm for configuration worker

---

src/oidcc_provider_configuration_worker.erl
test/oidcc_provider_configuration_worker_test.erl

Given an empty key set, the logic to prevent refreshes for keys without `kid` triggers and are never reloaded. This changes the logic so that an empty set always refreshes.

Always refresh keys on empty JWK

---

include/oidcc.hrl

The typo caused an error when compiling projects that include oidcc.hrl.

Fix `-define` typo in oidcc.hrl

---

lib/oidcc/authorization.ex
src/oidcc_authorization.erl

Document PAR Telemetry Events

---

src/oidcc_auth_util.erl
src/oidcc_authorization.erl
src/oidcc_jwt_util.erl
test/oidcc_authorization_test.erl
test/oidcc_userinfo_test.erl

Fix DPoP with JWK Set

---

src/oidcc_http_util.erl

Some providers will return this content-type, which is just a JSON content-type with stronger guarantees, so it's safe to just treat it as regular JSON
https://webconcepts.info/concepts/media-type/application/jwk-set+json

Support `application/jwk-set+json` content-type

---

lib/oidcc.ex

While using `oidcc`, I noticed that one of the return types is duplicated. I wouldn't really define it as a bug, so I labelled it as an "improvement". 😄

Remove duplicate return type in create_redirect_url spec

---

src/oidcc_provider_configuration_worker.erl

Prevent jwks_expired flood in worker 2nd try

---

src/oidcc_token_introspection.erl
test/oidcc_token_introspection_test.erl

resolves #364 
previously could only introspect a client_id's own token, introspect needs to be able to introspect any token for an issuer.
It is my understanding from https://datatracker.ietf.org/doc/html/rfc7662 that introspect endpoint is valid for use with any token from the issuer, however the code prior to this change would reject a token when the client_id in the token was not the same as the client_id of the caller to introspect.

token introspect remove client id constraint

---

src/oidcc_authorization.erl
test/oidcc_authorization_SUITE.erl
test/oidcc_authorization_test.erl

This reverts partially commit 3b0b5221a0c88ad733a3ffc769b5acada70c2afd.
This commit started to fail the OIDC conformance suite: https://gitlab.com/paulswartz/ueberauth_oidcc_certification/-/pipelines/1391557144
In particular, the error is:
Required http request parameters and request object claims must match
```
Required parameter 'response_type' was not found in http request parameters
Required parameter 'client_id' was not found in http request parameters
```
`redirect_url` does not appear to be required, so we continue to leave that out.

fix: partially revert "Don't send the same parameters in query string and JWT for redirect URL (#360)"

---

.github/SECURITY.md

Update Security Policy

---

lib/oidcc.ex
lib/oidcc/token.ex
test/oidcc/token_test.exs
test/oidcc_SUITE.erl
test/oidcc_test.exs
test/oidcc_token_SUITE.erl

Fix Zitadel Audiences

---

.github/workflows/branch_main.yml
.github/workflows/part_docs.yml
.github/workflows/part_publish.yml
.github/workflows/part_release.yml
.github/workflows/part_test.yml
.github/workflows/pr.yml
.github/workflows/tag-beta.yml
.github/workflows/tag-stable.yml

CI Improvements

---

lib/oidcc/client_context.ex

These incorrect types were causing dialyzer to fail in our consuming application code that had a case statement on the return value of `from_configuration_worker/3`.

fix: correct types in client_context.ex

---

src/oidcc_token.erl
test/oidcc_token_test.erl

Fixes https://github.com/erlef/oidcc/discussions/398

Check if PKCE is supported when exchanging token

---

lib/oidcc/token.ex
src/oidcc_token.erl
test/oidcc/token_test.exs
test/oidcc_token_test.erl

Validate arguments to validate_jwt fn

---

elvis.config
src/oidcc_token.erl

Cleanup duplicated code around oidcc_token:validate_jwt/3

---

lib/oidcc/logout.ex
test/oidcc/logout_test.exs

Handle Token Struct in Logout.initiate_url/3

---

README.md
lib/mix/tasks/oidcc.gen.provider_configuration_worker.ex
mix.exs
test/mix/tasks/oidcc.gen.provider_configuration_worker_test.exs

Basis for tasks following in `oidcc_plug`.

Igniter Setup

---

src/oidcc_decode_util.erl

Handle undefined values from provider's config in extract
Fixes https://github.com/erlef/oidcc/issues/470

Extract undefined from provider config
