erlef/oidcc

- src/oidcc_openid_provider.erl
up to 5 times the configuration is fetch in case of communication errors.
the gun is shut-down gracefully to ensure there is no 'DOWN' message arriving when everything went well.
> add multiple tries to fetch provider config

- src/oidcc.erl
- src/oidcc_http_util.erl
- src/oidcc_openid_provider.erl
- test/oidcc_http_util_test.erl
- test/oidcc_openid_provider_test.erl
- test/oidcc_test.erl
all gun related functionality is now in oidcc_http_util,
also change the tests accordingly
> extract common functionality into one module

- src/oidcc.erl
so the api documentation can be generated using 'make edoc'
> add source documentation

- src/oidcc.erl
use a qs list and cow_lib, instead of constructing binary body,
add selection of auth_method
> fix header

- src/oidcc.erl
- test/oidcc_test.erl
> Change scope

- src/oidcc.erl
- src/oidcc_token.erl
- test/oidcc_test.erl
- test/oidcc_token_test.erl
fix typo in subject verification at user_info
> Add verification of azp claim in case the audience is a list

- src/oidcc_session.erl
- src/oidcc_session_mgr.erl
- test/oidc_SUITE.erl
- test/oidcc_session_mgr_test.erl
also fixing a deadlock and unexpected behaviour of the session manager
> add tests for session management

- src/oidcc_http_handler.erl
Rename ClientMod to ClientModId to show that it is a Id and not the module name.
Close session in Handle Fail and handle return.
> Ensure oidcc_client:failed gets called on any kind of expected error

- example/basic_client/priv/templates/basic_client.dtl
- example/basic_client/src/basic_client.erl
- src/oidcc_http_handler.erl
- src/oidcc_session.erl
cookies can now enabled by a setting oidcc, use_cookie or by setting a flag in the redirection.
the default is not to use them.
the session code is refactored to be more generic and have less code
> Add possibility to use cookies

- rebar.config
> move back to original rebar lint

- src/oidcc_token.erl
not only check for audience being a list but instead check if it is the only
client.
Fix #51
> check for other audience

- src/oidcc_http_handler.erl
- src/oidcc_session.erl
integrate the oidcc callback into the TTS
> Tts integration

- src/oidcc_openid_provider.erl
- test/oidc_SUITE.erl
> Fix issuer verification

- Makefile
- src/oidcc_openid_provider.erl
> ensure the issuer of an IdToken is exactly equal to the issuer

- src/oidcc_openid_provider.erl
even if bad things happen or Provider is unrachable
fix #83
> ensure the configuration gets fetched 

- src/oidcc.erl
- src/oidcc_openid_provider.erl
- test/oidcc_openid_provider_mgr_test.erl
- test/oidcc_openid_provider_test.erl
> basic dynamic registration

- src/oidcc_openid_provider.erl
> accept http status in range [200, 300)

- src/oidcc_openid_provider.erl
> ensure expire of secret is a number

- conformance/priv/static/index.html
- conformance/src/conformance.erl
- conformance/src/conformance_http.erl
add test implementation, 
add more info regarding other profiles
part of #82
> passing 94% of code conformance tests

- src/oidcc.erl
- src/oidcc_token.erl
> add parameter wether 'none' algorithm is allowed

- src/oidcc_openid_provider.erl
- test/oidcc_openid_provider_test.erl
> ensure the provider supports the library

- conformance/config/sys.config
- conformance/priv/static/index.html
- conformance/rebar.config
- conformance/src/conformance.erl
- conformance/src/conformance_oidc_client.erl
use latest oidcc
update TODO on index.html
now passing code 100%
working on config profile
part of #82
> update conformance testing

- conformance/Makefile
- conformance/priv/static/index.html
- conformance/src/conformance.erl
- conformance/src/conformance_app.erl
> add automated testing

- conformance/utils/run_tests.sh
> add test runner script

- src/oidcc_openid_provider.erl
- test/oidc_SUITE.erl
- test/oidcc_openid_provider_test.erl
> do not use timer anymore

- src/oidcc.erl
- src/oidcc_openid_provider.erl
> add possibility to pass registration parameter

- src/oidcc_token.erl
> ensure keys get refetched

- src/oidcc_token.erl
> add missing conversion from ID -> Pid

- src/oidcc_openid_provider.erl
> fetching keys must not affect readyness of provider

- conformance/config/sys.config
- conformance/priv/static/index.html
- conformance/src/conformance.erl
- conformance/src/conformance_app.erl
part of #82 
need to check issue with SSL verification and read logs for each test to ensure the server also 
is satisfied
> conformance tests are passing

- conformance/src/conformance.erl
- conformance/src/conformance_app.erl
part of #82 
due to issues with TLS
> Conformance

- conformance/priv/readme.txt
- conformance/src/conformance_app.erl
- conformance/utils/run_tests.sh
> add readme for conformance results

- .gitignore
- conformance/Makefile
- conformance/priv/readme.txt
- conformance/rebar.config
> finalize conformance testing, setting version to 1.0.1

- src/oidcc.erl
> fix naming issue

- src/oidcc_http_cache.erl
- test/oidcc_http_util_test.erl
> ensure http works with or without cache

- README.md
- src/oidcc_http_cache.erl
- src/oidcc_http_util.erl
> Request timeout

- src/oidcc_token.erl
I came across several OpenIdConnect providers that did not support RS256 and only HS256. Since the basic support for those was already in `erljwt` I decided to implement the missing parts.
I did not add any tests yet, would you be so kind to take a look at it and provide some feedback. Most notably, I removed the default setting for `rs256` and switched that to the algo's suplied in the config. If needed by any of the supported algorithms, the `client secret` is added as an additional octet key.
The code has been tested against Auth0 on both `RS256` and `HS256`.
> Added support for HSXXX signing

- rebar.config
> Use patched coveralls version to fix reporting

- lib/oidcc.ex
- src/oidcc.erl
- src/oidcc_token.erl
- src/oidcc_token_introspection.erl
- src/oidcc_userinfo.erl
- test/oidcc/token_test.exs
- test/oidcc_token_test.erl
> Fix & Improve JWT / Response Validations

- README.md
> Link to oidcc_plug in README

- mix.exs
- rebar.config
> Cleanup rebar3 / mix Test Config

- lib/oidcc.ex
- lib/oidcc/token.ex
> Transform none_alg_used error to Elixir struct

- conformance/test.exs
> Simplify Conformance Testing using `oidcc_plug`

- priv/test/fixtures/example-metadata.json
- priv/test/fixtures/openid-certification-jwks.json
- src/oidcc_jwt_util.erl
- src/oidcc_token.erl
- src/oidcc_userinfo.erl
- test/oidcc_token_test.erl
> Fix HS256 Key Checking

- include/oidcc.hrl
- include/oidcc_client_registration.hrl
- lib/oidcc/client_registration.ex
- lib/oidcc/client_registration/response.ex
- priv/test/fixtures/example-metadata.json
- src/oidcc_client_registration.erl
- src/oidcc_decode_util.erl
- src/oidcc_http_util.erl
- src/oidcc_provider_configuration.erl
- test/oidcc/client_registration_test.exs
- test/oidcc_client_registration_test.erl
> Support OpenID Dynamic Client Registration

- priv/test/fixtures/example-metadata.json
- src/oidcc_client_registration.erl
- src/oidcc_jwt_util.erl
- src/oidcc_userinfo.erl
- test/oidcc/client_registration/response_test.exs
- test/oidcc_SUITE.erl
- test/oidcc_authorization_test.erl
- test/oidcc_client_registration_test.erl
- test/oidcc_provider_configuration_SUITE.erl
- test/oidcc_token_introspection_test.erl
- test/oidcc_userinfo_test.erl
> Improve Test Coverage

- include/oidcc_client_registration.hrl
- include/oidcc_provider_configuration.hrl
- lib/oidcc.ex
- lib/oidcc/client_registration.ex
- lib/oidcc/logout.ex
- lib/oidcc/provider_configuration.ex
- src/oidcc.erl
- src/oidcc_client_registration.erl
- src/oidcc_logout.erl
- src/oidcc_provider_configuration.erl
- test/oidcc/logout_test.exs
- test/oidcc_SUITE.erl
- test/oidcc_client_registration_test.erl
- test/oidcc_logout_test.erl
- test/oidcc_test.exs
> Implement RP Initiated Logout

- submitted_certifications/Erlang_Ecosystem_Foundation-oidcc-3rd_Party-Init_RP-20-Sep-2023.zip
- submitted_certifications/Erlang_Ecosystem_Foundation-oidcc-Basic_RP-19-Sept-2023.zip
- submitted_certifications/Erlang_Ecosystem_Foundation-oidcc-Config_RP-19-Sept-2023.zip
- submitted_certifications/Erlang_Ecosystem_Foundation-oidcc-Form_Post_Basic_RP-19-Sept-2023.zip
- submitted_certifications/Erlang_Ecosystem_Foundation-oidcc-RP_Initiated_RP_Basic-26-Sep-2023.zip
- submitted_certifications/Erlang_Ecosystem_Foundation-oidcc-Refresh_RP-20-Sept-2023.zip
> Certify v3.0.0

- README.md
> Mention certification in README

- src/oidcc_provider_configuration.erl
- test/oidcc_provider_configuration_SUITE.erl
Fix for https://github.com/erlef/oidcc/discussions/276#discussioncomment-7298477
> Prevent double slashes when concatenating URLs

- lib/oidcc/provider_configuration.ex
- src/oidcc_provider_configuration.erl
- test/oidcc_provider_configuration_SUITE.erl
- test/oidcc_provider_configuration_test.erl
> Introduce Quirks Options

- mix.exs
- rebar.config
> Call `edoc` directly from Mix

- rebar.config
- src/oidcc_token.erl
> Switch to stable erlfmt

- src/oidcc_provider_configuration.erl
- test/oidcc_provider_configuration_test.erl
> Fix URI composition for relative Issuer URIs without a trailing slash

- src/oidcc_token.erl
- test/oidcc_token_test.erl
> feat: `preferred_auth_methods` argument for `request_token`

- lib/oidcc/token/access.ex
- src/oidcc_token.erl
> doc: correct documentation for `oidcc_token:access()`

- src/oidcc_token.erl
- test/oidcc_token_test.erl
> Allow to pass url_extension for token retrieval

- .github/workflows/part_test.yml
- .tool-versions
> Update Test Elixir / OTP Versions

- README.md
- include/oidcc_provider_configuration.hrl
- lib/oidcc/token.ex
- priv/test/fixtures/fapi2-metadata.json
- src/oidcc_authorization.erl
- src/oidcc_jwt_util.erl
- src/oidcc_profile.erl
- src/oidcc_token.erl
- test/oidcc_authorization_test.erl
- test/oidcc_client_context_test.erl
- test/oidcc_token_test.erl
> feat: JARM

- src/oidcc_jwt_util.erl
- src/oidcc_token.erl
- test/oidcc_token_test.erl
> fix(jarm): check encryption/signature before validating claims

- README.md
Performed a security audit and shared results with Jonatan. This PR just puts a trace on the README about this.
> Update README.md to include the SAFE audit

- lib/oidcc.ex
- src/oidcc.erl
I had to dig through the code/tests to find that info :sweat_smile:
> Specify that `max_clock_skew` is in seconds

- .github/workflows/part_test.yml
- .tool-versions
- lib/oidcc.ex
- lib/oidcc/token.ex
- priv/test/fixtures/zitadel-client-credentials.json
- rebar.config
- test/oidcc/token_test.exs
- test/oidcc_SUITE.erl
- test/oidcc_http_util_SUITE.erl
- test/oidcc_test.exs
- test/oidcc_token_SUITE.erl
Waiting for Bob to build OTP 27 artifacts.
> Update to OTP 27

- test/oidcc/token_test.exs
- test/oidcc_SUITE.erl
- test/oidcc_test.exs
- test/oidcc_token_SUITE.erl
> Allow Clock Skew for Zitadel CT tests

- .github/workflows/part_test.yml
> Only export coverage for up to date OTP

- src/oidcc_provider_configuration_worker.erl
> Prevent jwks_expired flood in worker

- include/internal/doc.hrl
- mix.exs
- src/oidcc.erl
- src/oidcc_auth_util.erl
- src/oidcc_authorization.erl
- src/oidcc_backoff.erl
- src/oidcc_client_context.erl
- src/oidcc_client_registration.erl
- src/oidcc_decode_util.erl
- src/oidcc_http_util.erl
- src/oidcc_jwt_util.erl
- src/oidcc_logout.erl
- src/oidcc_profile.erl
- src/oidcc_provider_configuration.erl
- src/oidcc_provider_configuration_worker.erl
- src/oidcc_scope.erl
- src/oidcc_token.erl
- src/oidcc_token_introspection.erl
- src/oidcc_userinfo.erl
Formatting broken because of https://github.com/WhatsApp/erlfmt/issues/355.
Fix submitted: https://github.com/WhatsApp/erlfmt/pull/358
Ignoring errors for now.
> Switch to attribute based documentation

- src/oidcc_authorization.erl
> Fix Authorization Request Params

- .github/workflows/part_test.yml
- .tool-versions
> Update Erlang / Elixir in Dev Env / CI

- src/oidcc_token.erl
- test/oidcc_token_test.erl
Continuation of https://github.com/erlef/oidcc_plug/pull/33
> Relocate Key rotation into Token Validation

- lib/oidcc.ex
> Fix secret type for unauthenticated

- README.md
- include/oidcc_provider_configuration.hrl
- lib/oidcc/provider_configuration.ex
- src/oidcc_jwt_util.erl
- src/oidcc_provider_configuration.erl
- src/oidcc_token.erl
- test/oidcc_jwt_util_test.erl
- test/oidcc_provider_configuration_test.erl
- test/oidcc_token_test.erl
Fixes https://github.com/erlef/oidcc/issues/401
> Add a regex option for issuer validation

- lib/mix/tasks/oidcc.gen.provider_configuration_worker.ex
> Fix Optional Igniter

- README.md
> Update README.md for private_key_jwt usage

- .github/renovate.json
- .github/workflows/part_test.yml
- .tool-versions
- mix.exs
> Combined Updates

- .github/workflows/part_test.yml
- certification/config.json
> Logout Certification Testing

- priv/test/fixtures/example-config-optionals.json
- src/oidcc_provider_configuration.erl
- test/oidcc_provider_configuration_test.erl
> Set default for token_endpoint_auth_methods_supported
